SET SCHEMA %schemaName%;

CREATE TABLE EVENT_STORE
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    TYPE VARCHAR(32) NOT NULL,
    CREATED TIMESTAMP,
    PAYLOAD CLOB(10M),
    REMAINING_RETRIES INT NOT NULL,
    BLOCKED_UNTIL TIMESTAMP NOT NULL,
    ERROR VARCHAR(1000),
    CAMUNDA_TASK_ID VARCHAR(40),
    SYSTEM_ENGINE_IDENTIFIER VARCHAR(128),
    LOCK_EXPIRE TIMESTAMP NULL,
    CONSTRAINT EVENT_STORE_PKEY PRIMARY KEY (ID)
);

CREATE TABLE OUTBOX_SCHEMA_VERSION
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    VERSION VARCHAR(255) NOT NULL,
    CREATED TIMESTAMP NOT NULL,
    CONSTRAINT SCHEMA_VERSION_PKEY PRIMARY KEY (ID)
);

INSERT INTO OUTBOX_SCHEMA_VERSION (VERSION, CREATED) VALUES ('1.12.0', CURRENT_TIMESTAMP);

GRANT INSERT, UPDATE, SELECT, DELETE ON OUTBOX_SCHEMA_VERSION TO %camundaSchemaName%;
GRANT INSERT, UPDATE, SELECT, DELETE ON EVENT_STORE TO %camundaSchemaName%;
