/*
 * Copyright [2024] [envite consulting GmbH]
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *
 *
 */

package io.kadai.adapter.integration;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import io.kadai.adapter.camunda.outbox.rest.config.OutboxDataSource;
import io.kadai.adapter.camunda.outbox.rest.model.Camunda7TaskEvent;
import io.kadai.adapter.camunda.outbox.rest.resource.Camunda7TaskEventListResource;
import io.kadai.adapter.impl.scheduled.KadaiTaskCompletionOrchestrator;
import io.kadai.adapter.impl.scheduled.KadaiTaskStarterOrchestrator;
import io.kadai.adapter.systemconnector.camunda.api.impl.HttpHeaderProvider;
import io.kadai.adapter.test.KadaiAdapterTestApplication;
import io.kadai.common.api.security.UserPrincipal;
import io.kadai.common.test.security.JaasExtension;
import io.kadai.common.test.security.WithAccessId;
import io.kadai.common.test.util.ParallelThreadHelper;
import io.kadai.impl.configuration.DbCleaner;
import io.kadai.impl.configuration.DbCleaner.ApplicationDatabaseType;
import io.kadai.task.api.TaskState;
import io.kadai.task.api.models.TaskSummary;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.Callable;
import javax.security.auth.Subject;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.http.HttpHeaders;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.web.client.RestClientResponseException;

/** Test class to test the conversion of tasks generated by Camunda BPM to Kadai tasks. */
@SpringBootTest(
    classes = KadaiAdapterTestApplication.class,
    webEnvironment = WebEnvironment.DEFINED_PORT)
@AutoConfigureWebTestClient
@ExtendWith(JaasExtension.class)
@ContextConfiguration
@SuppressWarnings("checkstyle:LineLength")
class TestLockingAndClustering extends AbsIntegrationTest {

  private static final String BASIC_OUTBOX_PATH = "http://localhost:10020/outbox-rest/events";
  private static final String INSERT_EVENT =
      "INSERT INTO kadai_tables.event_store "
          + "(TYPE, CREATED, PAYLOAD, REMAINING_RETRIES, BLOCKED_UNTIL, CAMUNDA_TASK_ID, LOCK_EXPIRE) "
          + "VALUES (?, ?, ?, ?, ?, ?, ?)";
  @Autowired KadaiTaskStarterOrchestrator kadaiTaskStarter;
  @Autowired KadaiTaskCompletionOrchestrator kadaiTaskTerminator;
  @Autowired private HttpHeaderProvider httpHeaderProvider;
  private JdbcTemplate outboxJdbcTemplate;

  @BeforeEach
  @WithAccessId(user = "taskadmin")
  void initializeOutbox() {
    outboxJdbcTemplate = new JdbcTemplate(OutboxDataSource.get());
    clearOutbox();
  }

  @AfterEach
  @WithAccessId(user = "taskadmin")
  void resetOutbox() {
    clearOutbox();
  }

  @WithAccessId(
      user = "teamlead_1",
      groups = {"taskadmin"})
  @Test
  void should_LockEventsForTheCorrectTime_When_Getting() {
    insertEvent("create", "lock-timing", 0, Instant.now().plusSeconds(3600));

    String url = BASIC_OUTBOX_PATH + "?lock-for=1";

    HttpHeaders headers = httpHeaderProvider.getHttpHeadersForOutboxRestApi();
    Camunda7TaskEventListResource answer =
        restClient
            .get()
            .uri(url)
            .headers(httpHeaders -> httpHeaders.addAll(headers))
            .retrieve()
            .toEntity(Camunda7TaskEventListResource.class)
            .getBody();

    assertThat(answer).isNotNull();
    assertThat(answer.getCamunda7TaskEvents()).hasSize(1);
    answer =
        restClient
            .get()
            .uri(url)
            .headers(httpHeaders -> httpHeaders.addAll(headers))
            .retrieve()
            .toEntity(Camunda7TaskEventListResource.class)
            .getBody();

    assertThat(answer).isNotNull();
    assertThat(answer.getCamunda7TaskEvents()).isEmpty();

    try {
      Thread.sleep(1200);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
    answer =
        restClient
            .get()
            .uri(url)
            .headers(httpHeaders -> httpHeaders.addAll(headers))
            .retrieve()
            .toEntity(Camunda7TaskEventListResource.class)
            .getBody();

    assertThat(answer).isNotNull();
    assertThat(answer.getCamunda7TaskEvents()).hasSize(1);
  }

  @WithAccessId(
      user = "teamlead_1",
      groups = {"taskadmin"})
  @Test
  void should_UnlockTheEvent() {
    insertEvent("create", "unlock-test", 0, Instant.now().plusSeconds(3600));
    String urlWithLock = BASIC_OUTBOX_PATH + "?lock-for=10";

    HttpHeaders headers = httpHeaderProvider.getHttpHeadersForOutboxRestApi();
    Camunda7TaskEventListResource answer =
        restClient
            .get()
            .uri(urlWithLock)
            .headers(httpHeaders -> httpHeaders.addAll(headers))
            .retrieve()
            .toEntity(Camunda7TaskEventListResource.class)
            .getBody();
    assertThat(answer).isNotNull();
    assertThat(answer.getCamunda7TaskEvents()).hasSize(1);
    int eventId = answer.getCamunda7TaskEvents().getFirst().getId();
    String urlWithUnlock = BASIC_OUTBOX_PATH + "/unlock-event/" + eventId;

    restClient
        .post()
        .uri(urlWithUnlock)
        .headers(httpHeaders -> httpHeaders.addAll(headers))
        .retrieve()
        .toEntity(Void.class);
    answer =
        restClient
            .get()
            .uri(urlWithLock)
            .headers(httpHeaders -> httpHeaders.addAll(headers))
            .retrieve()
            .toEntity(Camunda7TaskEventListResource.class)
            .getBody();
    assertThat(answer).isNotNull();
    assertThat(answer.getCamunda7TaskEvents()).hasSize(1);
  }

  @WithAccessId(
      user = "teamlead_1",
      groups = {"taskadmin"})
  @Test
  void should_ReturnOnlyEligibleCreateEvents_When_FilteringByType() {
    insertEvent("create", "create-ready", 3, Instant.now().minusSeconds(60));
    insertEvent("create", "create-blocked", 3, Instant.now().plusSeconds(60));
    insertEvent("create", "create-exhausted", 0, Instant.now().minusSeconds(60));
    insertEvent("complete", "complete-ready", 3, Instant.now().minusSeconds(60));

    Camunda7TaskEventListResource answer = getEventListResource(BASIC_OUTBOX_PATH + "?type=create");

    assertThat(answer).isNotNull();
    assertThat(answer.getCamunda7TaskEvents())
        .extracting(Camunda7TaskEvent::getCamundaTaskId)
        .containsExactly("create-ready");
    assertThat(answer.getCamunda7TaskEvents())
        .extracting(Camunda7TaskEvent::getType)
        .containsOnly("create");
  }

  @WithAccessId(
      user = "teamlead_1",
      groups = {"taskadmin"})
  @Test
  void should_ReturnOnlyCompleteAndDeleteEvents_When_FilteringByTypes() {
    insertEvent("create", "create-ready", 3, Instant.now().minusSeconds(60));
    insertEvent("complete", "complete-ready", 3, Instant.now().minusSeconds(60));
    insertEvent("delete", "delete-ready", 3, Instant.now().minusSeconds(60));

    Camunda7TaskEventListResource answer =
        getEventListResource(BASIC_OUTBOX_PATH + "?type=complete&type=delete");

    assertThat(answer).isNotNull();
    assertThat(answer.getCamunda7TaskEvents())
        .extracting(Camunda7TaskEvent::getCamundaTaskId)
        .containsExactlyInAnyOrder("complete-ready", "delete-ready");
    assertThat(answer.getCamunda7TaskEvents())
        .extracting(Camunda7TaskEvent::getType)
        .containsExactlyInAnyOrder("complete", "delete");
  }

  @WithAccessId(
      user = "teamlead_1",
      groups = {"taskadmin"})
  @Test
  void should_FilterByRetriesWithoutLeakingOtherUnlockedEvents_When_LockingFilteredEvents() {
    insertEvent("create", "retry-one", 1, Instant.now().minusSeconds(60));
    insertEvent("complete", "retry-two", 2, Instant.now().minusSeconds(60));

    Camunda7TaskEventListResource answer =
        getEventListResource(BASIC_OUTBOX_PATH + "?retries=1&lock-for=10");

    assertThat(answer).isNotNull();
    assertThat(answer.getCamunda7TaskEvents())
        .extracting(Camunda7TaskEvent::getCamundaTaskId)
        .containsExactly("retry-one");

    Camunda7TaskEventListResource lockedAnswer =
        getEventListResource(BASIC_OUTBOX_PATH + "?retries=1&lock-for=10");
    assertThat(lockedAnswer).isNotNull();
    assertThat(lockedAnswer.getCamunda7TaskEvents()).isEmpty();

    Camunda7TaskEventListResource differentRetriesAnswer =
        getEventListResource(BASIC_OUTBOX_PATH + "?retries=2");
    assertThat(differentRetriesAnswer).isNotNull();
    assertThat(differentRetriesAnswer.getCamunda7TaskEvents())
        .extracting(Camunda7TaskEvent::getCamundaTaskId)
        .containsExactly("retry-two");
  }

  @WithAccessId(
      user = "teamlead_1",
      groups = {"taskadmin"})
  @Test
  void should_RejectUnknownFilterParameters() {
    assertThatThrownBy(() -> executeGet(BASIC_OUTBOX_PATH + "?unexpected=value"))
        .isInstanceOfSatisfying(
            RestClientResponseException.class,
            exception -> {
              assertThat(exception.getStatusCode().value()).isEqualTo(400);
              assertThat(exception.getResponseBodyAsString())
                  .contains("Provided invalid request params: [unexpected]");
            });
  }

  @WithAccessId(
      user = "teamlead_1",
      groups = {"taskadmin"})
  @Test
  void should_RejectInvalidRetriesAndLockDurationParameters() {
    assertThatThrownBy(() -> executeGet(BASIC_OUTBOX_PATH + "?retries=not-a-number"))
        .isInstanceOfSatisfying(
            RestClientResponseException.class,
            exception -> {
              assertThat(exception.getStatusCode().value()).isEqualTo(400);
              assertThat(exception.getResponseBodyAsString())
                  .contains("retries param must be of type Integer!");
            });

    assertThatThrownBy(() -> executeGet(BASIC_OUTBOX_PATH + "?lock-for=-1"))
        .isInstanceOfSatisfying(
            RestClientResponseException.class,
            exception -> {
              assertThat(exception.getStatusCode().value()).isEqualTo(400);
              assertThat(exception.getResponseBodyAsString())
                  .contains("lock-for param must be of type non-negative Integer!");
            });
  }

  @WithAccessId(user = "taskadmin")
  @Test
  void should_CreateCorrespondingKadaiTasksConcurrently() throws Exception {
    String processInstanceId =
        this.camundaProcessengineRequester.startCamundaProcessAndReturnId(
            "simple_multiple_execution_process", "");
    List<String> accessIds =
        Collections.synchronizedList(new ArrayList<>(List.of("admin", "taskadmin")));
    Callable<Void> action =
        () -> {
          kadaiTaskStarter.retrieveReferencedTasksAndCreateCorrespondingKadaiTasks();
          return null;
        };
    ParallelThreadHelper.runInThread(getRunnableTest(accessIds, action), accessIds.size());
    List<String> camundaTaskIds =
        this.camundaProcessengineRequester.getTaskIdsFromProcessInstanceId(processInstanceId);
    assertThat(camundaTaskIds).hasSize(3);
    for (String externalId : camundaTaskIds) {
      List<TaskSummary> tasks = taskService.createTaskQuery().externalIdIn(externalId).list();
      assertThat(tasks).hasSize(1);
    }
  }

  @WithAccessId(user = "taskadmin")
  @Test
  void should_FinishCorrespondingKadaiTasksConcurrently() throws Exception {
    String processInstanceId =
        this.camundaProcessengineRequester.startCamundaProcessAndReturnId(
            "simple_multiple_execution_process", "");
    List<String> camundaTaskIds =
        this.camundaProcessengineRequester.getTaskIdsFromProcessInstanceId(processInstanceId);
    assertThat(camundaTaskIds).hasSize(3);
    Thread.sleep((long) (this.adapterTaskPollingInterval * 1.2));

    for (String camundaTaskId : camundaTaskIds) {
      this.camundaProcessengineRequester.completeTaskWithId(camundaTaskId);
    }
    List<String> accessIds =
        Collections.synchronizedList(
            new ArrayList<>(List.of("taskadmin", "taskadmin", "taskadmin")));
    Callable<Void> action =
        () -> {
          kadaiTaskTerminator.retrieveFinishedReferencedTasksAndTerminateCorrespondingKadaiTasks();
          return null;
        };
    ParallelThreadHelper.runInThread(getRunnableTest(accessIds, action), accessIds.size());
    for (String externalId : camundaTaskIds) {
      List<TaskSummary> tasks = taskService.createTaskQuery().externalIdIn(externalId).list();
      assertThat(tasks).hasSize(1);
      assertThat(tasks.getFirst().getState()).isEqualTo(TaskState.COMPLETED);
    }
  }

  private Runnable getRunnableTest(List<String> accessIds, Callable<Void> action) {
    return () -> {
      Subject subject = new Subject();
      subject.getPrincipals().add(new UserPrincipal(accessIds.removeFirst()));
      Subject.callAs(subject, action);
    };
  }

  private void insertEvent(
      String type, String camundaTaskId, int remainingRetries, Instant blockedUntil) {
    Timestamp created = Timestamp.from(Instant.now().minusSeconds(60));
    Timestamp blockedUntilTimestamp = Timestamp.from(blockedUntil);

    outboxJdbcTemplate.update(
        INSERT_EVENT,
        type,
        created,
        "{\"id\":\"" + camundaTaskId + "\"}",
        remainingRetries,
        blockedUntilTimestamp,
        camundaTaskId,
        null);
  }

  private Camunda7TaskEventListResource getEventListResource(String url) {
    HttpHeaders headers = httpHeaderProvider.getHttpHeadersForOutboxRestApi();
    return restClient
        .get()
        .uri(url)
        .headers(httpHeaders -> httpHeaders.addAll(headers))
        .retrieve()
        .toEntity(Camunda7TaskEventListResource.class)
        .getBody();
  }

  private void executeGet(String url) {
    HttpHeaders headers = httpHeaderProvider.getHttpHeadersForOutboxRestApi();
    restClient
        .get()
        .uri(url)
        .headers(httpHeaders -> httpHeaders.addAll(headers))
        .retrieve()
        .body(String.class);
  }

  private void clearOutbox() {
    DbCleaner cleaner = new DbCleaner();
    cleaner.clearDb(camundaBpmDataSource, ApplicationDatabaseType.OUTBOX);
  }
}
